# config/_default/params.toml

[header]
  enable_language_switcher = true

[social]
  github = "masa10223"
  email = "mtsutsumi@tara.tsukuba.ac.jp"
  location = "Tsukuba, Ibaraki, Japan"
  org = "University of Tsukuba (TARA)"

[appearance]
  mode = "dark"
  color = "blue"

[pagination]
  pagerSize = 10

[license]
  enable = true
  text = "CC BY-NC-ND 4.0"
  url  = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[footer]
  copyright = "Â© 2025 Masato Tsutsumi"
